name: shake
description: A flutter package to detect phone shakes. Adjustable G-force and reset periods.
version: 2.2.0
homepage: https://www.github.com/deven98/shake

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sensors_plus: ^6.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

